# Data Cleaning

## 1. Steam Dataset Cleaning

## 2. VGChartz Dataset Cleaning

In [2]:
import pandas as pd
import numpy as np
import json
import ast

pd.set_option("display.max_columns", None)

In [3]:
with open("../data/raw/games.json", "r", encoding="utf-8") as f:
    steam_data = json.load(f)

In [4]:
steam = pd.DataFrame.from_dict(
    steam_data,
    orient="index"
)

In [5]:
steam.index.name = "appid"

steam = steam.reset_index()

In [6]:
steam.head()

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,header_image,website,support_url,support_email,windows,mac,linux,metacritic_score,metacritic_url,achievements,recommendations,notes,supported_languages,full_audio_languages,packages,developers,publishers,categories,genres,screenshots,movies,user_score,score_rank,positive,negative,estimated_owners,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0,0.00,0,,,,,https://shared.akamai.steamstatic.com/store_it...,,,,True,False,False,0,,0,0,,[],[],[],[],[],[],[],[https://shared.akamai.steamstatic.com/store_i...,[],0,,0,0,0 - 0,0,0,0,0,0,0,[]
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0,5.24,0,"Springtime, April: when the cherry trees come ...","Springtime, April: when the cherry trees come ...","Spring has come, and our protagonist, Yukinari...",,https://shared.akamai.steamstatic.com/store_it...,http://mangagamer.org/supipara,http://mangagamer.com,support@mangagamer.com,True,False,False,0,,0,231,,[English],[],[{'title': 'Buy Supipara - Chapter 1 Spring Ha...,[minori],[MangaGamer],"[Single-player, Steam Trading Cards, Steam Clo...",[Adventure],[https://shared.akamai.steamstatic.com/store_i...,[],0,,252,3,0 - 20000,8,0,8,0,65,0,"{'Adventure': 27, 'Visual Novel': 19, 'Anime':..."
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0,4.99,0,"Immerse yourself in the most beloved, mystical...","Immerse yourself in the most beloved, mystical...",Discover an entrancing and spectacular world!,,https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,support@8floor.net,True,True,False,0,,0,0,,"[English, French, German, Russian]",[],[{'title': 'Buy Mystery Solitaire The Black Ra...,[Somer Games],[8floor],"[Single-player, Family Sharing]",[Casual],[https://shared.akamai.steamstatic.com/store_i...,[],0,,21,3,0 - 20000,0,0,0,0,0,0,"{'Casual': 83, 'Card Game': 52, 'Solitaire': 4..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0,8.99,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",Yuha! I'll start the broadcast! Hakko's extrem...,,https://shared.akamai.steamstatic.com/store_it...,,,yujingamesc@gmail.com,True,False,False,0,,19,0,The game includes the following elements. 1. G...,[Korean],[Korean],"[{'title': 'Buy 버튜버 파라노이아 - Vtuber Paranoia', ...",[유진게임즈],[유진게임즈],"[Single-player, Steam Achievements, Family Sha...","[Casual, Indie, Simulation]",[https://shared.akamai.steamstatic.com/store_i...,[],0,,0,0,0 - 20000,0,0,0,0,0,1,[]
4,3631080,Maze Quest VR,"Apr 24, 2025",0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,Its not just a Maze; its a Quest! Enter the ca...,,https://shared.akamai.steamstatic.com/store_it...,https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,support@realityexpanded.com,True,False,False,0,,0,0,,[English],[English],"[{'title': 'Buy Maze Quest VR', 'description':...",[Reality Expanded LLC],[Reality Expanded LLC],"[Single-player, VR Only, Steam Leaderboards, F...","[Action, Early Access]",[https://shared.akamai.steamstatic.com/store_i...,[],0,,0,0,0 - 20000,0,0,0,0,0,0,[]

In [7]:
steam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135043 entries, 0 to 135042
Data columns (total 43 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   appid                     135043 non-null  object
 1   name                      135043 non-null  object
 2   release_date              135043 non-null  object
 3   required_age              135043 non-null  int64
 4   price                     135043 non-null  float64
 5   dlc_count                 135043 non-null  int64
 6   detailed_description      135043 non-null  object
 7   about_the_game            135043 non-null  object
 8   short_description         135043 non-null  object
 9   reviews                   135043 non-null  object
 10  header_image              135043 non-null  object
 11  website                   135043 non-null  object
 12  support_url               135043 non-null  object
 13  support_email             135043 non-null  object
 14  windows                   135043 non-null  bool
 15  mac                       135043 non-null  bool
 16  linux                     135043 non-null  bool
 17  metacritic_score          135043 non-null  int64
 18  metacritic_url            135043 non-null  object
 19  achievements              135043 non-null  int64
 20  recommendations           135043 non-null  int64
 21  notes                     135043 non-null  object
 22  supported_languages       135043 non-null  object
 23  full_audio_languages      135043 non-null  object
 24  packages                  135043 non-null  object
 25  developers                135043 non-null  object
 26  publishers                135043 non-null  object
 27  categories                135043 non-null  object
 28  genres                    135043 non-null  object
 29  screenshots               135043 non-null  object
 30  movies                    135043 non-null  object
 31  user_score                135043 non-null  int64
 32  score_rank                135043 non-null  object
 33  positive                  135043 non-null  int64
 34  negative                  135043 non-null  int64
 35  estimated_owners          135043 non-null  object
 36  average_playtime_forever  135043 non-null  int64
 37  average_playtime_2weeks   135043 non-null  int64
 38  median_playtime_forever   135043 non-null  int64
 39  median_playtime_2weeks    135043 non-null  int64
 40  discount                  135043 non-null  object
 41  peak_ccu                  135043 non-null  int64
 42  tags                      135043 non-null  object
dtypes: bool(3), float64(1), int64(13), object(26)
memory usage: 41.6+ MB

In [8]:
steam.columns = (
    steam.columns
    .str.lower()
    .str.replace(" ", "_")
)

In [9]:
steam.columns

Index(['appid', 'name', 'release_date', 'required_age', 'price', 'dlc_count',
       'detailed_description', 'about_the_game', 'short_description',
       'reviews', 'header_image', 'website', 'support_url', 'support_email',
       'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url',
       'achievements', 'recommendations', 'notes', 'supported_languages',
       'full_audio_languages', 'packages', 'developers', 'publishers',
       'categories', 'genres', 'screenshots', 'movies', 'user_score',
       'score_rank', 'positive', 'negative', 'estimated_owners',
       'average_playtime_forever', 'average_playtime_2weeks',
       'median_playtime_forever', 'median_playtime_2weeks', 'discount',
       'peak_ccu', 'tags'],
      dtype='object')

In [10]:
remove_columns = [
    "header_image",
    "website",
    "support_url",
    "support_email",
    "detailed_description",
    "about_the_game",
    "short_description",
    "metacritic_url",
    "screenshots",
    "movies",
    "notes"
]

steam = steam.drop(
    columns=remove_columns,
    errors="ignore"
)

In [11]:
steam["release_date"].head()

0     Aug 1, 2023
1    Jul 29, 2016
2     May 6, 2019
3    Oct 31, 2024
4    Apr 24, 2025
Name: release_date, dtype: object

In [12]:
steam["release_date"] = pd.to_datetime(
    steam["release_date"],
    errors="coerce"
)

In [13]:
steam["release_year"] = (
    steam["release_date"]
    .dt.year
)

In [14]:
steam = steam[
    (steam["release_year"] >= 2018) &
    (steam["release_year"] <= 2024)
]

In [15]:
steam["price"].describe()

count    81517.000000
mean         4.758614
std         13.882386
min          0.000000
25%          0.490000
50%          1.990000
75%          4.990000
max        999.980000
Name: price, dtype: float64

In [16]:
steam[
    steam["price"] > 200
]

,appid,name,release_date,required_age,price,dlc_count,reviews,windows,mac,linux,metacritic_score,achievements,recommendations,supported_languages,full_audio_languages,packages,developers,publishers,categories,genres,user_score,score_rank,positive,negative,estimated_owners,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,release_year
31935,3013840,True Love,2024-06-27,0,500.00,0,,True,False,False,0,0,0,[English],[],"[{'title': 'Buy True Love', 'description': '',...",[A Guy],[Whoes heart broken],"[Single-player, Family Sharing]","[Action, Adventure, Casual, Indie]",0,,3,1,0 - 20000,0,0,0,0,0,0,"{'Casual': 413, 'Action-Adventure': 387, 'Visu...",2024
34463,1200520,Ascent Free-Roaming VR Experience,2019-12-27,0,999.00,0,,True,False,False,0,0,0,[English],[English],[{'title': 'Buy Ascent Free-Roaming VR Experie...,[Fury VR],[Zenland Video Games],"[Single-player, Multi-player, Co-op, LAN Co-op...",[Action],0,,6,1,0 - 20000,0,0,0,0,0,0,"{'Action': 95, 'Hentai': 41, 'Nudity': 36, 'Se...",2019
41088,2504210,The Leverage Game Business Edition,2023-08-26,0,999.98,0,,True,False,False,0,0,0,"[English, Japanese]","[English, Japanese]",[{'title': 'Buy The Leverage Game Business Edi...,[A&S Inc.],[A&S Inc.],"[Single-player, Multi-player, PvP, Family Shar...","[Indie, Simulation]",0,,0,0,0 - 20000,0,0,0,0,0,0,[],2023
68275,2499620,The Leverage Game,2023-08-25,0,999.98,0,,True,False,False,0,0,0,"[English, Japanese]","[English, Japanese]","[{'title': 'Buy The Leverage Game', 'descripti...",[A&S Inc.],[A&S Inc.],"[Single-player, Multi-player, PvP, Online PvP,...","[Indie, Simulation]",0,,1,0,0 - 20000,0,0,0,0,0,0,"{'Board Game': 48, 'Turn-Based Tactics': 42, '...",2023
77652,1105450,Aartform Curvy 3D 4.0,2020-01-20,0,299.99,0,,True,False,False,0,0,0,[English],[],"[{'title': 'Buy Aartform Curvy 3D 4.0', 'descr...",[Aartform Ltd],[Aartform Ltd],[],"[Animation & Modeling, Design & Illustration]",0,,10,2,0 - 20000,0,0,0,0,0,0,"{'Design & Illustration': 22, 'Animation & Mod...",2020
102212,502570,Houdini Indie,2018-10-10,0,269.99,0,,True,True,False,0,0,235,[English],[],"[{'title': 'Yearly Subscription', 'description...",[SideFX],[SideFX],"[Partial Controller Support, Steam Cloud]","[Animation & Modeling, Design & Illustration, ...",0,,233,18,0 - 20000,242,0,242,0,0,59,"{'Animation & Modeling': 65, 'Game Development...",2018

In [17]:
steam.loc[
    steam["price"] > 200,
    "price"
] = np.nan

In [18]:
def owner_midpoint(value):
    if pd.isna(value):
        return np.nan
    
    value = value.replace(",", "")
    
    lower, upper = value.split("-")
    
    return (
        int(lower.strip()) +
        int(upper.strip())
    ) / 2

In [19]:
steam["estimated_players"] = (
    steam["estimated_owners"]
    .apply(owner_midpoint)
)

In [20]:
steam["total_reviews"] = (
    steam["positive"]
    +
    steam["negative"]
)

In [21]:
steam["review_score"] = np.where(
    steam["total_reviews"] > 0,
    steam["positive"] /
    steam["total_reviews"],
    np.nan
)

In [22]:
steam["genres"] = steam["genres"].apply(
    lambda x: x if isinstance(x, list)
    else []
)

In [23]:
steam.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81517 entries, 0 to 134936
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   appid                     81517 non-null  object
 1   name                      81517 non-null  object
 2   release_date              81517 non-null  datetime64[ns]
 3   required_age              81517 non-null  int64
 4   price                     81511 non-null  float64
 5   dlc_count                 81517 non-null  int64
 6   reviews                   81517 non-null  object
 7   windows                   81517 non-null  bool
 8   mac                       81517 non-null  bool
 9   linux                     81517 non-null  bool
 10  metacritic_score          81517 non-null  int64
 11  achievements              81517 non-null  int64
 12  recommendations           81517 non-null  int64
 13  supported_languages       81517 non-null  object
 14  full_audio_languages      81517 non-null  object
 15  packages                  81517 non-null  object
 16  developers                81517 non-null  object
 17  publishers                81517 non-null  object
 18  categories                81517 non-null  object
 19  genres                    81517 non-null  object
 20  user_score                81517 non-null  int64
 21  score_rank                81517 non-null  object
 22  positive                  81517 non-null  int64
 23  negative                  81517 non-null  int64
 24  estimated_owners          81517 non-null  object
 25  average_playtime_forever  81517 non-null  int64
 26  average_playtime_2weeks   81517 non-null  int64
 27  median_playtime_forever   81517 non-null  int64
 28  median_playtime_2weeks    81517 non-null  int64
 29  discount                  81517 non-null  object
 30  peak_ccu                  81517 non-null  int64
 31  tags                      81517 non-null  object
 32  release_year              81517 non-null  int32
 33  estimated_players         81517 non-null  float64
 34  total_reviews             81517 non-null  int64
 35  review_score              61234 non-null  float64
dtypes: bool(3), datetime64[ns](1), float64(3), int32(1), int64(14), object(14)
memory usage: 21.1+ MB

In [24]:
steam.isna().sum()

appid                           0
name                            0
release_date                    0
required_age                    0
price                           6
dlc_count                       0
reviews                         0
windows                         0
mac                             0
linux                           0
metacritic_score                0
achievements                    0
recommendations                 0
supported_languages             0
full_audio_languages            0
packages                        0
developers                      0
publishers                      0
categories                      0
genres                          0
user_score                      0
score_rank                      0
positive                        0
negative                        0
estimated_owners                0
average_playtime_forever        0
average_playtime_2weeks         0
median_playtime_forever         0
median_playtime_2weeks          0
discount                        0
peak_ccu                        0
tags                            0
release_year                    0
estimated_players               0
total_reviews                   0
review_score                20283
dtype: int64

In [25]:
missing = pd.DataFrame({
    "missing_count": steam.isna().sum(),
    "missing_percentage": (
        steam.isna().sum() / len(steam) * 100
    )
})

missing.sort_values(
    "missing_percentage",
    ascending=False
)

                          missing_count  missing_percentage
review_score                      20283           24.881926
price                                 6            0.007360
median_playtime_forever               0            0.000000
score_rank                            0            0.000000
positive                              0            0.000000
negative                              0            0.000000
estimated_owners                      0            0.000000
average_playtime_forever              0            0.000000
average_playtime_2weeks               0            0.000000
median_playtime_2weeks                0            0.000000
genres                                0            0.000000
discount                              0            0.000000
peak_ccu                              0            0.000000
tags                                  0            0.000000
release_year                          0            0.000000
estimated_players                     0            0.000000
total_reviews                         0            0.000000
user_score                            0            0.000000
appid                                 0            0.000000
name                                  0            0.000000
linux                                 0            0.000000
release_date                          0            0.000000
required_age                          0            0.000000
dlc_count                             0            0.000000
reviews                               0            0.000000
windows                               0            0.000000
mac                                   0            0.000000
metacritic_score                      0            0.000000
publishers                            0            0.000000
achievements                          0            0.000000
recommendations                       0            0.000000
supported_languages                   0            0.000000
full_audio_languages                  0            0.000000
packages                              0            0.000000
developers                            0            0.000000
categories                            0            0.000000

In [26]:
steam.to_csv(
    "../data/cleaned/steam_cleaned.csv",
    index=False
)

In [27]:
import pandas as pd
import numpy as np

vgchartz = pd.read_csv(
    "../data/raw/vgchartz-2024.csv"
)

vgchartz.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [28]:
vgchartz.shape

(64016, 14)

In [29]:
vgchartz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

In [30]:
vgchartz.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [31]:
vgchartz["total_sales"].describe()

count    18922.000000
mean         0.349113
std          0.807462
min          0.000000
25%          0.030000
50%          0.120000
75%          0.340000
max         20.320000
Name: total_sales, dtype: float64

In [32]:
vgchartz[vgchartz["total_sales"].isna()].head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
18922,/games/boxart/full_5741036AmericaFrontccc.jpg,God of War,Series,Action,Sony Interactive Entertainment,SIE Santa Monica Studio,NaN,NaN,NaN,NaN,NaN,NaN,2005-03-22,2020-03-04
18923,/games/boxart/full_3351915AmericaFrontccc.jpg,Warriors,Series,Action,KOEI,Omega Force,NaN,NaN,NaN,NaN,NaN,NaN,1997-06-30,2020-03-24
18924,/games/boxart/full_6662824AmericaFrontccc.png,Devil May Cry,Series,Action,Capcom,Capcom,NaN,NaN,NaN,NaN,NaN,NaN,2001-10-16,2020-02-03
18925,/games/boxart/full_8122622AmericaFrontccc.jpg,God of War (2018),All,Action,Sony Interactive Entertainment,SIE Santa Monica Studio,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-20,2022-11-23
18926,/games/boxart/full_6138740AmericaFrontccc.jpg,Dynasty Warriors,Series,Action,KOEI,Omega Force,NaN,NaN,NaN,NaN,NaN,NaN,1997-06-30,2020-03-24

In [33]:
vgchartz["critic_score"].notna().sum()

6678

In [34]:
vgchartz["developer"] = (
    vgchartz["developer"]
    .fillna("Unknown")
)

In [35]:
vgchartz["release_date"] = pd.to_datetime(
    vgchartz["release_date"],
    errors="coerce"
)

In [36]:
vgchartz["release_date"].isna().sum()

7051

In [37]:
vgchartz = vgchartz.drop(
    columns=["last_update"],
    errors="ignore"
)

In [38]:
vgchartz.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000,56965
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041,2006-11-14 06:33:03.491617792
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1971-12-03 00:00:00
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000,2001-03-28 00:00:00
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000,2008-09-16 00:00:00
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000,2012-12-27 00:00:00
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000,2024-12-31 00:00:00
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643,NaN

In [39]:
vgchartz["release_year"] = (
    vgchartz["release_date"]
    .dt.year
)

In [40]:
vgchartz["release_year"].value_counts().sort_index()

release_year
1971.0       1
1973.0       1
1975.0       1
1977.0      11
1978.0      45
1979.0       8
1980.0      35
1981.0      50
1982.0     214
1983.0     298
1984.0     102
1985.0     101
1986.0     159
1987.0     270
1988.0     294
1989.0     426
1990.0     657
1991.0     779
1992.0     933
1993.0    1034
1994.0    1163
1995.0    1153
1996.0    1228
1997.0    1040
1998.0    1096
1999.0    1272
2000.0    1552
2001.0    1478
2002.0    1726
2003.0    1723
2004.0    1606
2005.0    1810
2006.0    2096
2007.0    2525
2008.0    2936
2009.0    4360
2010.0    3586
2011.0    3386
2012.0    1584
2013.0    1740
2014.0    2896
2015.0    1680
2016.0    1352
2017.0    1558
2018.0    1538
2019.0    1290
2020.0    1452
2021.0     422
2022.0     168
2023.0     108
2024.0      22
Name: count, dtype: int64

In [41]:
sales_sum = (
    vgchartz["na_sales"].fillna(0)
    + vgchartz["jp_sales"].fillna(0)
    + vgchartz["pal_sales"].fillna(0)
    + vgchartz["other_sales"].fillna(0)
)

(vgchartz["total_sales"] - sales_sum).describe()

count    18922.000000
mean         0.000238
std          0.004898
min         -0.020000
25%          0.000000
50%          0.000000
75%          0.000000
max          0.020000
dtype: float64

In [42]:
vgchartz["release_year"] = (
    vgchartz["release_year"]
    .astype("Int64")
)

In [43]:
vgchartz = vgchartz.drop(
    columns=["img"]
)

In [44]:
vgchartz.head()

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,release_year
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,2013
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2014
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,2002
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,2013
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2015

In [45]:
vgchartz.to_csv(
    "../data/cleaned/vgchartz_cleaned.csv",
    index=False
)

In [46]:
vgchartz.isna().sum()

title               0
console             0
genre               0
publisher           0
developer           0
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
release_year     7051
dtype: int64